export const locales = ["zh-Hant", "zh-Hans", "en", "ja", "ko"] as const;
export type Locale = (typeof locales)[number];
const en = { title: "Bastet Workstation", milestone: "M3 office vertical slice", navigation: "Primary navigation", office: "Office", agents: "Agents and Models", approvals: "Approval Center", diagnostics: "Diagnostics", officeHelp: "Preview every accessible Pet state before applying the first-party profile.", builtinPet: "Built-in Pet catalog", applyPet: "Apply Pet", rollbackPet: "Roll back Pet", applied: "Applied", notApplied: "Not applied", prepareMvp: "Prepare MVP project", projectName: "Project name", workspaceRoot: "Absolute workspace directory", prepare: "Prepare meeting", decisionBaseline: "Decision baseline", acceptDecision: "Accept decision and compile graph", documentTitle: "Document title", documentMarkdown: "Markdown document", createDocument: "Create joined document", acceptDocument: "Accept exact document version", rooms: "Rooms", meetings: "Meetings", documents: "Documents", costs: "Cost records", agentHelp: "Review installation, health, authentication, models, reasoning, and run controls before starting work.", approvalHelp: "Approval cards show the exact immutable action, reason, consequence, risk, and expiry.", noApprovals: "No pending or recent approvals.", configured: "Reference adapter", doctor: "Doctor", authentication: "Authentication", models: "Models", reasoning: "Reasoning", runControl: "Run controls", sessionsAndRuns: "Sessions and runs", sessions: "Sessions", revision: "Revision", noRuns: "No runs.", cancel: "Cancel", cancelRejected: "Cancellation was not accepted.", available: "Available after local check", verifyLocally: "Verify locally", providerReported: "Provider reported", installed: "Installed", notInstalled: "Not installed", version: "Version", unknown: "Unknown", unavailable: "Unavailable", authenticated: "Authenticated", notAuthenticated: "Not authenticated", risk: "Risk", expires: "Expires", approve: "Approve", deny: "Deny", approved: "Approved", denied: "Denied", connecting: "Connecting to local daemon", ready: "Local daemon connected", offline: "Local daemon unavailable", retry: "Reconnect", autostart: "Start automatically at login (opt-in)" } as const;
const delivery = { prepareMemory: "Prepare AgentMemoryOS capture", prepareMind: "Prepare BastetMind publish", knowledgeDeliveries: "Knowledge deliveries", prepared: "Prepared", delivered: "Delivered", runReady: "Run ready graph work" } as const;
export type MessageKey = keyof typeof en | keyof typeof delivery;
const deliveryLocales: Record<Locale, Record<keyof typeof delivery, string>> = {
  en: delivery,
  "zh-Hant": { prepareMemory: "準備擷取至 AgentMemoryOS", prepareMind: "準備發布至 BastetMind", knowledgeDeliveries: "知識交付", prepared: "已準備", delivered: "已送達", runReady: "執行已就緒的 Graph 工作" },
  "zh-Hans": { prepareMemory: "准备捕获到 AgentMemoryOS", prepareMind: "准备发布到 BastetMind", knowledgeDeliveries: "知识交付", prepared: "已准备", delivered: "已送达", runReady: "运行已就绪的 Graph 工作" },
  ja: { prepareMemory: "AgentMemoryOS への保存を準備", prepareMind: "BastetMind への公開を準備", knowledgeDeliveries: "ナレッジ配信", prepared: "準備済み", delivered: "配信済み", runReady: "準備済みの Graph 作業を実行" },
  ko: { prepareMemory: "AgentMemoryOS 캡처 준비", prepareMind: "BastetMind 게시 준비", knowledgeDeliveries: "지식 전달", prepared: "준비됨", delivered: "전달됨", runReady: "준비된 Graph 작업 실행" },
};
const messages: Record<Locale, Partial<Record<MessageKey, string>>> = {
  en: { ...en, ...delivery },
  "zh-Hant": { ...en, milestone: "M3 Office 垂直切片", navigation: "主要導覽", office: "辦公室", agents: "Agents 與模型", approvals: "核准中心", diagnostics: "診斷", officeHelp: "套用第一方 Pet 前，先預覽所有具有可及性文字的狀態。", builtinPet: "內建 Pet 目錄", applyPet: "套用 Pet", rollbackPet: "回復 Pet", applied: "已套用", notApplied: "未套用", prepareMvp: "準備 MVP 專案", projectName: "專案名稱", workspaceRoot: "絕對工作目錄", prepare: "準備會議", decisionBaseline: "決策基線", acceptDecision: "接受決策並編譯 Graph", rooms: "房間", meetings: "會議", documents: "文件", costs: "成本紀錄", agentHelp: "開始工作前，請檢查安裝、健康狀態、驗證、模型、推理與執行控制。", approvalHelp: "核准卡會顯示不可變更的動作、原因、後果、風險與到期時間。", noApprovals: "目前沒有待處理或近期核准。", configured: "參考 Adapter", doctor: "健康檢查", authentication: "驗證", models: "模型", reasoning: "推理", runControl: "執行控制", sessionsAndRuns: "工作階段與執行", sessions: "工作階段", revision: "修訂版", noRuns: "目前沒有執行。", cancel: "取消", cancelRejected: "供應商未接受取消要求。", available: "本機檢查後可用", verifyLocally: "在本機驗證", providerReported: "供應商回報", risk: "風險", expires: "到期", approve: "核准", deny: "拒絕", approved: "已核准", denied: "已拒絕", connecting: "正在連接本機服務", ready: "本機服務已連線", offline: "本機服務無法連線", retry: "重新連線", autostart: "登入時自動啟動（選用）" },
  "zh-Hans": { ...en, milestone: "M3 Office 垂直切片", navigation: "主导航", office: "办公室", agents: "Agents 与模型", approvals: "批准中心", diagnostics: "诊断", officeHelp: "应用第一方 Pet 前，预览全部带无障碍文字的状态。", builtinPet: "内置 Pet 目录", applyPet: "应用 Pet", rollbackPet: "回退 Pet", applied: "已应用", notApplied: "未应用", rooms: "房间", meetings: "会议", documents: "文档", costs: "成本记录", noApprovals: "没有待处理或近期批准。", sessionsAndRuns: "会话与运行", sessions: "会话", revision: "修订版", noRuns: "当前没有运行。", cancel: "取消", cancelRejected: "提供方未接受取消请求。", approve: "批准", deny: "拒绝", approved: "已批准", denied: "已拒绝" },
  ja: { ...en, milestone: "M3 Office 垂直スライス", navigation: "メインナビゲーション", office: "オフィス", agents: "Agents とモデル", approvals: "承認センター", diagnostics: "診断", officeHelp: "適用前に、アクセシブルな説明付きの全 Pet 状態を確認します。", builtinPet: "組み込み Pet カタログ", applyPet: "Pet を適用", rollbackPet: "Pet を戻す", applied: "適用済み", notApplied: "未適用", rooms: "部屋", meetings: "会議", documents: "文書", costs: "コスト記録", noApprovals: "保留中または最近の承認はありません。", sessionsAndRuns: "セッションと実行", sessions: "セッション", revision: "リビジョン", noRuns: "実行はありません。", cancel: "キャンセル", cancelRejected: "プロバイダーがキャンセルを受け付けませんでした。", approve: "承認", deny: "拒否", approved: "承認済み", denied: "拒否済み" },
  ko: { ...en, milestone: "M3 Office 수직 슬라이스", navigation: "기본 탐색", office: "오피스", agents: "Agents 및 모델", approvals: "승인 센터", diagnostics: "진단", officeHelp: "적용 전에 접근성 설명이 있는 모든 Pet 상태를 미리 봅니다.", builtinPet: "내장 Pet 카탈로그", applyPet: "Pet 적용", rollbackPet: "Pet 롤백", applied: "적용됨", notApplied: "적용 안 됨", rooms: "방", meetings: "회의", documents: "문서", costs: "비용 기록", noApprovals: "대기 중이거나 최근 승인이 없습니다.", sessionsAndRuns: "세션 및 실행", sessions: "세션", revision: "리비전", noRuns: "실행이 없습니다.", cancel: "취소", cancelRejected: "공급자가 취소 요청을 수락하지 않았습니다.", approve: "승인", deny: "거부", approved: "승인됨", denied: "거부됨" },
};
export function translate(locale: Locale, key: MessageKey): string { return deliveryLocales[locale]?.[key as keyof typeof delivery] ?? messages[locale]?.[key] ?? messages.en[key] ?? `[missing:${key}]`; }
