export const locales = ["zh-Hant", "zh-Hans", "en", "ja", "ko"] as const;
export type Locale = (typeof locales)[number];
const en = { title: "Bastet Workstation", milestone: "M3 office vertical slice", navigation: "Primary navigation", office: "Office", agents: "Agents and Models", approvals: "Approval Center", diagnostics: "Diagnostics", officeHelp: "Preview every accessible Pet state before applying the first-party profile.", builtinPet: "Built-in Pet catalog", applyPet: "Apply Pet", rollbackPet: "Roll back Pet", applied: "Applied", notApplied: "Not applied", prepareMvp: "Prepare MVP project", projectName: "Project name", workspaceRoot: "Absolute workspace directory", prepare: "Prepare meeting", decisionBaseline: "Decision baseline", acceptDecision: "Accept decision and compile graph", documentTitle: "Document title", documentMarkdown: "Markdown document", createDocument: "Create joined document", acceptDocument: "Accept exact document version", rooms: "Rooms", meetings: "Meetings", documents: "Documents", costs: "Cost records", agentHelp: "Review installation, health, authentication, models, reasoning, and run controls before starting work.", approvalHelp: "Approval cards show the exact immutable action, reason, consequence, risk, and expiry.", noApprovals: "No pending or recent approvals.", configured: "Reference adapter", doctor: "Doctor", authentication: "Authentication", models: "Models", reasoning: "Reasoning", runControl: "Run controls", sessionsAndRuns: "Sessions and runs", sessions: "Sessions", revision: "Revision", noRuns: "No runs.", cancel: "Cancel", cancelRejected: "Cancellation was not accepted.", available: "Available after local check", verifyLocally: "Verify locally", providerReported: "Provider reported", installed: "Installed", notInstalled: "Not installed", version: "Version", unknown: "Unknown", unavailable: "Unavailable", authenticated: "Authenticated", notAuthenticated: "Not authenticated", risk: "Risk", expires: "Expires", approve: "Approve", deny: "Deny", approved: "Approved", denied: "Denied", connecting: "Connecting to local daemon", ready: "Local daemon connected", offline: "Local daemon unavailable", retry: "Reconnect", autostart: "Start automatically at login (opt-in)" } as const;
const delivery = { prepareMemory: "Prepare AgentMemoryOS capture", prepareMind: "Prepare BastetMind publish", knowledgeDeliveries: "Knowledge deliveries", prepared: "Prepared", delivered: "Delivered", runReady: "Run ready graph work", deliverNow: "Deliver now", working: "Work is in progress…", actionFailed: "The action could not be confirmed. Refresh its status before trying again.", graphOutputMissing: "Graph work completed, but no joined document output is available.", retryMissingOutputHelp: "Outputs from an older run are unavailable. Retrying creates a new run; existing published content remains, while its regenerated replacement needs new acceptance and delivery.", retryMissingOutputs: "Retry missing graph outputs", retryFailedNode: "Retry failed work", retryFailedNodeHelp: "Retries only this failed work. Its blocked join continues after it succeeds.", failureUnknown: "This work failed. The provider did not supply a safe classification.", failureProviderUnavailable: "This work failed because the provider is unavailable.", failureProviderTimeout: "This work failed because the provider timed out.", failureProviderCrashed: "This work failed because the provider stopped unexpectedly.", failureProviderAuthentication: "This work failed because provider authentication needs attention.", failureProviderQuota: "This work failed because the provider quota has been reached.", failureProviderRejected: "This work was rejected by the provider.", failureInvalidOutput: "This work returned an unusable result.", failureCancelled: "This work was cancelled.", failureInterrupted: "This work was interrupted.", exportDocument: "Export accepted document", workspaceFile: "Workspace file" } as const;
const approval = { approvalIdentity: "Approval identity", approvalScope: "Requested scope", agentInstance: "Agent instance", agentProvider: "Agent provider", role: "Role", requestedPolicy: "Requested policy", policyLayer: "Policy layer", policyLayerWorkstation: "Workstation", policyLayerProject: "Project", policyLayerRoleOrAgent: "Role or agent", policyLayerSingleRun: "Single run", filesystem: "Filesystem", network: "Network", process: "Process", device: "Device", credential: "Credential", persistentApproval: "Persistent approval", permissionDeny: "Deny", permissionObserve: "Observe", permissionUse: "Use", yes: "Yes", no: "No", unknown: "Unknown", project: "Project", run: "Run", filesystemRoots: "Filesystem roots", dataScopes: "Data scopes", networkDestinations: "Network destinations", credentialReferences: "Credential references", destination: "Destination", none: "None", credentialBinding: "Credential binding", singleUseCredential: "Single-use credential approval", providerIdentity: "Provider identity", adapter: "Adapter", account: "Account", accountLabel: "Account label", credentialReference: "Credential reference", capability: "Capability", backend: "Credential backend", service: "Credential service", credentialScopeNote: "This approves one use of the displayed credential reference before the expiry above. It does not authenticate or sign in to the provider." } as const;
const lifecycleLocales = {
  en: { quitBlocked: "The app could not quit safely. Wait for active work to finish or cancel it in Agents and Models, then try quitting again." },
  "zh-Hant": { quitBlocked: "程式尚無法安全結束。請等待工作完成，或到「Agents 與模型」取消執行中的工作，再重試結束程式。" },
  "zh-Hans": { quitBlocked: "程序暂时无法安全退出。请等待工作完成，或到“Agents 与模型”取消运行中的工作，再尝试退出。" },
  ja: { quitBlocked: "安全に終了できませんでした。作業の完了を待つか、「Agents とモデル」で実行中の作業をキャンセルしてから、終了を再試行してください。" },
  ko: { quitBlocked: "앱을 안전하게 종료하지 못했습니다. 작업이 끝날 때까지 기다리거나 ‘Agents 및 모델’에서 실행 중인 작업을 취소한 뒤 종료를 다시 시도하세요." },
} as const;
export type MessageKey = keyof typeof en | keyof typeof delivery | keyof typeof approval | keyof typeof lifecycleLocales.en;
const approvalLocales: Record<Locale, Record<keyof typeof approval, string>> = {
  en: approval,
  "zh-Hant": { approvalIdentity: "核准身分", approvalScope: "請求範圍", agentInstance: "Agent 執行個體", agentProvider: "Agent 供應商", role: "角色", requestedPolicy: "請求的政策", policyLayer: "政策層級", policyLayerWorkstation: "工作站", policyLayerProject: "專案", policyLayerRoleOrAgent: "角色或 Agent", policyLayerSingleRun: "單次執行", filesystem: "檔案系統", network: "網路", process: "程序", device: "裝置", credential: "憑證", persistentApproval: "持續核准", permissionDeny: "拒絕", permissionObserve: "僅觀察", permissionUse: "使用", yes: "是", no: "否", unknown: "未知", project: "專案", run: "執行", filesystemRoots: "檔案系統根目錄", dataScopes: "資料範圍", networkDestinations: "網路目的地", credentialReferences: "憑證參照", destination: "目的地", none: "無", credentialBinding: "憑證繫結", singleUseCredential: "單次使用憑證核准", providerIdentity: "供應商身分", adapter: "Adapter", account: "帳戶", accountLabel: "帳戶標籤", credentialReference: "憑證參照", capability: "能力", backend: "憑證後端", service: "憑證服務", credentialScopeNote: "此核准只允許在上述到期時間前使用所顯示的憑證參照一次；它不會驗證或登入供應商。" },
  "zh-Hans": { approvalIdentity: "批准身份", approvalScope: "请求范围", agentInstance: "Agent 实例", agentProvider: "Agent 提供方", role: "角色", requestedPolicy: "请求的策略", policyLayer: "策略层级", policyLayerWorkstation: "工作站", policyLayerProject: "项目", policyLayerRoleOrAgent: "角色或 Agent", policyLayerSingleRun: "单次运行", filesystem: "文件系统", network: "网络", process: "进程", device: "设备", credential: "凭据", persistentApproval: "持续批准", permissionDeny: "拒绝", permissionObserve: "仅观察", permissionUse: "使用", yes: "是", no: "否", unknown: "未知", project: "项目", run: "运行", filesystemRoots: "文件系统根目录", dataScopes: "数据范围", networkDestinations: "网络目标", credentialReferences: "凭据引用", destination: "目标", none: "无", credentialBinding: "凭据绑定", singleUseCredential: "单次使用凭据批准", providerIdentity: "提供方身份", adapter: "适配器", account: "账户", accountLabel: "账户标签", credentialReference: "凭据引用", capability: "能力", backend: "凭据后端", service: "凭据服务", credentialScopeNote: "此批准仅允许在上述到期前使用所显示的凭据引用一次；它不会验证或登录提供方。" },
  ja: { approvalIdentity: "承認の識別情報", approvalScope: "要求されたスコープ", agentInstance: "Agent インスタンス", agentProvider: "Agent プロバイダー", role: "ロール", requestedPolicy: "要求されたポリシー", policyLayer: "ポリシーレイヤー", policyLayerWorkstation: "ワークステーション", policyLayerProject: "プロジェクト", policyLayerRoleOrAgent: "ロールまたは Agent", policyLayerSingleRun: "単一実行", filesystem: "ファイルシステム", network: "ネットワーク", process: "プロセス", device: "デバイス", credential: "認証情報", persistentApproval: "継続的な承認", permissionDeny: "拒否", permissionObserve: "観察のみ", permissionUse: "使用", yes: "はい", no: "いいえ", unknown: "不明", project: "プロジェクト", run: "実行", filesystemRoots: "ファイルシステムのルート", dataScopes: "データスコープ", networkDestinations: "ネットワーク宛先", credentialReferences: "認証情報の参照", destination: "宛先", none: "なし", credentialBinding: "認証情報のバインディング", singleUseCredential: "一回限りの認証情報の承認", providerIdentity: "プロバイダーの識別情報", adapter: "アダプター", account: "アカウント", accountLabel: "アカウントラベル", credentialReference: "認証情報の参照", capability: "機能", backend: "認証情報バックエンド", service: "認証情報サービス", credentialScopeNote: "この承認は、上記の有効期限まで表示された認証情報の参照を一度だけ使用できます。プロバイダーへの認証やログインは行いません。" },
  ko: { approvalIdentity: "승인 식별 정보", approvalScope: "요청 범위", agentInstance: "Agent 인스턴스", agentProvider: "Agent 제공자", role: "역할", requestedPolicy: "요청된 정책", policyLayer: "정책 계층", policyLayerWorkstation: "워크스테이션", policyLayerProject: "프로젝트", policyLayerRoleOrAgent: "역할 또는 Agent", policyLayerSingleRun: "단일 실행", filesystem: "파일 시스템", network: "네트워크", process: "프로세스", device: "장치", credential: "자격 증명", persistentApproval: "지속 승인", permissionDeny: "거부", permissionObserve: "관찰만", permissionUse: "사용", yes: "예", no: "아니요", unknown: "알 수 없음", project: "프로젝트", run: "실행", filesystemRoots: "파일 시스템 루트", dataScopes: "데이터 범위", networkDestinations: "네트워크 대상", credentialReferences: "자격 증명 참조", destination: "대상", none: "없음", credentialBinding: "자격 증명 바인딩", singleUseCredential: "일회용 자격 증명 승인", providerIdentity: "제공자 식별 정보", adapter: "어댑터", account: "계정", accountLabel: "계정 레이블", credentialReference: "자격 증명 참조", capability: "기능", backend: "자격 증명 백엔드", service: "자격 증명 서비스", credentialScopeNote: "이 승인은 위 만료 시각 전까지 표시된 자격 증명 참조를 한 번만 사용할 수 있습니다. 제공자 인증 또는 로그인을 수행하지 않습니다." },
};
const deliveryLocales: Record<Locale, Record<keyof typeof delivery, string>> = {
  en: delivery,
  "zh-Hant": { prepareMemory: "準備擷取至 AgentMemoryOS", prepareMind: "準備發布至 BastetMind", knowledgeDeliveries: "知識交付", prepared: "已準備", delivered: "已送達", runReady: "執行已就緒的 Graph 工作", deliverNow: "立即交付", working: "工作執行中…", actionFailed: "操作結果無法確認。請先重新確認狀態，再決定是否重試。", graphOutputMissing: "Graph 工作已完成，但沒有可用的合併文件輸出。", retryMissingOutputHelp: "舊執行的輸出已不可用；重試會建立新的執行。現有已發布內容會保留，重新產生的結果則需要重新接受與交付。", retryMissingOutputs: "重試缺少的 Graph 輸出", retryFailedNode: "重試失敗的工作", retryFailedNodeHelp: "只會重試這項失敗工作；成功後，被阻擋的合併會繼續。", failureUnknown: "這項工作失敗，供應商未提供可安全顯示的分類。", failureProviderUnavailable: "這項工作失敗，因為供應商無法使用。", failureProviderTimeout: "這項工作失敗，因為供應商逾時。", failureProviderCrashed: "這項工作失敗，因為供應商意外停止。", failureProviderAuthentication: "這項工作失敗，因為供應商驗證需要處理。", failureProviderQuota: "這項工作失敗，因為已達供應商額度。", failureProviderRejected: "這項工作遭供應商拒絕。", failureInvalidOutput: "這項工作傳回無法使用的結果。", failureCancelled: "這項工作已取消。", failureInterrupted: "這項工作已中斷。", exportDocument: "匯出已接受的文件", workspaceFile: "工作區檔案" },
  "zh-Hans": { prepareMemory: "准备捕获到 AgentMemoryOS", prepareMind: "准备发布到 BastetMind", knowledgeDeliveries: "知识交付", prepared: "已准备", delivered: "已送达", runReady: "运行已就绪的 Graph 工作", deliverNow: "立即交付", working: "工作进行中…", actionFailed: "操作结果无法确认。请先重新确认状态，再决定是否重试。", graphOutputMissing: "Graph 工作已完成，但没有可用的合并文档输出。", retryMissingOutputHelp: "旧运行的输出已不可用；重试会创建新的运行。现有已发布内容会保留，重新生成的结果需要重新接受和交付。", retryMissingOutputs: "重试缺失的 Graph 输出", retryFailedNode: "重试失败工作", retryFailedNodeHelp: "只重试这项失败工作；成功后，受阻的合并会继续。", failureUnknown: "这项工作失败，提供方未提供可安全显示的分类。", failureProviderUnavailable: "这项工作失败，因为提供方不可用。", failureProviderTimeout: "这项工作失败，因为提供方超时。", failureProviderCrashed: "这项工作失败，因为提供方意外停止。", failureProviderAuthentication: "这项工作失败，因为提供方身份验证需要处理。", failureProviderQuota: "这项工作失败，因为已达到提供方额度。", failureProviderRejected: "这项工作被提供方拒绝。", failureInvalidOutput: "这项工作返回了不可用的结果。", failureCancelled: "这项工作已取消。", failureInterrupted: "这项工作已中断。", exportDocument: "导出已接受的文档", workspaceFile: "工作区文件" },
  ja: { prepareMemory: "AgentMemoryOS への保存を準備", prepareMind: "BastetMind への公開を準備", knowledgeDeliveries: "ナレッジ配信", prepared: "準備済み", delivered: "配信済み", runReady: "準備済みの Graph 作業を実行", deliverNow: "今すぐ配信", working: "処理中です…", actionFailed: "操作結果を確認できませんでした。再試行する前に最新の状態を確認してください。", graphOutputMissing: "Graph 作業は完了しましたが、統合文書の出力を利用できません。", retryMissingOutputHelp: "古い実行の出力は利用できません。再試行すると新しい実行を作成します。既存の公開済みコンテンツは残り、再生成結果は新たな承認と配信が必要です。", retryMissingOutputs: "不足した Graph 出力を再試行", retryFailedNode: "失敗した作業を再試行", retryFailedNodeHelp: "この失敗した作業だけを再試行します。成功後、ブロックされた統合が続行されます。", failureUnknown: "この作業は失敗しました。安全に表示できる分類がプロバイダーから提供されていません。", failureProviderUnavailable: "プロバイダーを利用できないため、この作業は失敗しました。", failureProviderTimeout: "プロバイダーがタイムアウトしたため、この作業は失敗しました。", failureProviderCrashed: "プロバイダーが予期せず停止したため、この作業は失敗しました。", failureProviderAuthentication: "プロバイダー認証に対応が必要なため、この作業は失敗しました。", failureProviderQuota: "プロバイダーの利用枠に達したため、この作業は失敗しました。", failureProviderRejected: "この作業はプロバイダーに拒否されました。", failureInvalidOutput: "この作業は利用できない結果を返しました。", failureCancelled: "この作業はキャンセルされました。", failureInterrupted: "この作業は中断されました。", exportDocument: "承認済み文書をエクスポート", workspaceFile: "ワークスペースファイル" },
  ko: { prepareMemory: "AgentMemoryOS 캡처 준비", prepareMind: "BastetMind 게시 준비", knowledgeDeliveries: "지식 전달", prepared: "준비됨", delivered: "전달됨", runReady: "준비된 Graph 작업 실행", deliverNow: "지금 전달", working: "작업 진행 중…", actionFailed: "작업 결과를 확인하지 못했습니다. 다시 시도하기 전에 최신 상태를 확인하세요.", graphOutputMissing: "Graph 작업은 완료되었지만 병합 문서 출력을 사용할 수 없습니다.", retryMissingOutputHelp: "이전 실행의 출력은 사용할 수 없습니다. 다시 시도하면 새 실행이 생성됩니다. 기존 게시 콘텐츠는 유지되며, 재생성 결과는 새 승인과 전달이 필요합니다.", retryMissingOutputs: "누락된 Graph 출력 다시 시도", retryFailedNode: "실패한 작업 다시 시도", retryFailedNodeHelp: "이 실패한 작업만 다시 시도합니다. 성공하면 차단된 병합이 계속됩니다.", failureUnknown: "이 작업은 실패했습니다. 공급자가 안전하게 표시할 분류를 제공하지 않았습니다.", failureProviderUnavailable: "공급자를 사용할 수 없어 이 작업이 실패했습니다.", failureProviderTimeout: "공급자가 시간 초과되어 이 작업이 실패했습니다.", failureProviderCrashed: "공급자가 예기치 않게 중지되어 이 작업이 실패했습니다.", failureProviderAuthentication: "공급자 인증에 조치가 필요하여 이 작업이 실패했습니다.", failureProviderQuota: "공급자 할당량에 도달하여 이 작업이 실패했습니다.", failureProviderRejected: "공급자가 이 작업을 거부했습니다.", failureInvalidOutput: "이 작업이 사용할 수 없는 결과를 반환했습니다.", failureCancelled: "이 작업이 취소되었습니다.", failureInterrupted: "이 작업이 중단되었습니다.", exportDocument: "승인된 문서 내보내기", workspaceFile: "작업 공간 파일" },
};
const workflowKeys = ["prepareMvp", "projectName", "workspaceRoot", "prepare", "decisionBaseline", "acceptDecision", "documentTitle", "documentMarkdown", "createDocument", "acceptDocument"] as const;
type WorkflowKey = (typeof workflowKeys)[number];
const workflowLocales: Record<Locale, Record<WorkflowKey, string>> = {
  en: { prepareMvp: "Prepare MVP project", projectName: "Project name", workspaceRoot: "Absolute workspace directory", prepare: "Prepare meeting", decisionBaseline: "Decision baseline", acceptDecision: "Accept decision and compile graph", documentTitle: "Document title", documentMarkdown: "Markdown document", createDocument: "Create joined document", acceptDocument: "Accept exact document version" },
  "zh-Hant": { prepareMvp: "準備 MVP 專案", projectName: "專案名稱", workspaceRoot: "絕對工作目錄", prepare: "準備會議", decisionBaseline: "決策基線", acceptDecision: "接受決策並編譯 Graph", documentTitle: "文件標題", documentMarkdown: "Markdown 文件", createDocument: "建立合併文件", acceptDocument: "接受此精確文件版本" },
  "zh-Hans": { prepareMvp: "准备 MVP 项目", projectName: "项目名称", workspaceRoot: "绝对工作目录", prepare: "准备会议", decisionBaseline: "决策基线", acceptDecision: "接受决策并编译 Graph", documentTitle: "文档标题", documentMarkdown: "Markdown 文档", createDocument: "创建合并文档", acceptDocument: "接受此精确文档版本" },
  ja: { prepareMvp: "MVP プロジェクトを準備", projectName: "プロジェクト名", workspaceRoot: "絶対ワークスペースパス", prepare: "会議を準備", decisionBaseline: "意思決定ベースライン", acceptDecision: "決定を承認して Graph をコンパイル", documentTitle: "文書タイトル", documentMarkdown: "Markdown 文書", createDocument: "統合文書を作成", acceptDocument: "この文書バージョンを承認" },
  ko: { prepareMvp: "MVP 프로젝트 준비", projectName: "프로젝트 이름", workspaceRoot: "절대 작업 공간 경로", prepare: "회의 준비", decisionBaseline: "의사결정 기준선", acceptDecision: "결정을 승인하고 Graph 컴파일", documentTitle: "문서 제목", documentMarkdown: "Markdown 문서", createDocument: "통합 문서 만들기", acceptDocument: "이 정확한 문서 버전 승인" },
};
const messages: Record<Locale, Partial<Record<MessageKey, string>>> = {
  en: { ...en, ...delivery },
  "zh-Hant": { ...en, milestone: "M3 Office 垂直切片", navigation: "主要導覽", office: "辦公室", agents: "Agents 與模型", approvals: "核准中心", diagnostics: "診斷", officeHelp: "套用第一方 Pet 前，先預覽所有具有可及性文字的狀態。", builtinPet: "內建 Pet 目錄", applyPet: "套用 Pet", rollbackPet: "回復 Pet", applied: "已套用", notApplied: "未套用", prepareMvp: "準備 MVP 專案", projectName: "專案名稱", workspaceRoot: "絕對工作目錄", prepare: "準備會議", decisionBaseline: "決策基線", acceptDecision: "接受決策並編譯 Graph", rooms: "房間", meetings: "會議", documents: "文件", costs: "成本紀錄", agentHelp: "開始工作前，請檢查安裝、健康狀態、驗證、模型、推理與執行控制。", approvalHelp: "核准卡會顯示不可變更的動作、原因、後果、風險與到期時間。", noApprovals: "目前沒有待處理或近期核准。", configured: "參考 Adapter", doctor: "健康檢查", authentication: "驗證", models: "模型", reasoning: "推理", runControl: "執行控制", sessionsAndRuns: "工作階段與執行", sessions: "工作階段", revision: "修訂版", noRuns: "目前沒有執行。", cancel: "取消", cancelRejected: "供應商未接受取消要求。", available: "本機檢查後可用", verifyLocally: "在本機驗證", providerReported: "供應商回報", risk: "風險", expires: "到期", approve: "核准", deny: "拒絕", approved: "已核准", denied: "已拒絕", connecting: "正在連接本機服務", ready: "本機服務已連線", offline: "本機服務無法連線", retry: "重新連線", autostart: "登入時自動啟動（選用）" },
  "zh-Hans": { ...en, milestone: "M3 Office 垂直切片", navigation: "主导航", office: "办公室", agents: "Agents 与模型", approvals: "批准中心", diagnostics: "诊断", officeHelp: "应用第一方 Pet 前，预览全部带无障碍文字的状态。", builtinPet: "内置 Pet 目录", applyPet: "应用 Pet", rollbackPet: "回退 Pet", applied: "已应用", notApplied: "未应用", rooms: "房间", meetings: "会议", documents: "文档", costs: "成本记录", noApprovals: "没有待处理或近期批准。", sessionsAndRuns: "会话与运行", sessions: "会话", revision: "修订版", noRuns: "当前没有运行。", cancel: "取消", cancelRejected: "提供方未接受取消请求。", approve: "批准", deny: "拒绝", approved: "已批准", denied: "已拒绝" },
  ja: { ...en, milestone: "M3 Office 垂直スライス", navigation: "メインナビゲーション", office: "オフィス", agents: "Agents とモデル", approvals: "承認センター", diagnostics: "診断", officeHelp: "適用前に、アクセシブルな説明付きの全 Pet 状態を確認します。", builtinPet: "組み込み Pet カタログ", applyPet: "Pet を適用", rollbackPet: "Pet を戻す", applied: "適用済み", notApplied: "未適用", rooms: "部屋", meetings: "会議", documents: "文書", costs: "コスト記録", noApprovals: "保留中または最近の承認はありません。", sessionsAndRuns: "セッションと実行", sessions: "セッション", revision: "リビジョン", noRuns: "実行はありません。", cancel: "キャンセル", cancelRejected: "プロバイダーがキャンセルを受け付けませんでした。", approve: "承認", deny: "拒否", approved: "承認済み", denied: "拒否済み" },
  ko: { ...en, milestone: "M3 Office 수직 슬라이스", navigation: "기본 탐색", office: "오피스", agents: "Agents 및 모델", approvals: "승인 센터", diagnostics: "진단", officeHelp: "적용 전에 접근성 설명이 있는 모든 Pet 상태를 미리 봅니다.", builtinPet: "내장 Pet 카탈로그", applyPet: "Pet 적용", rollbackPet: "Pet 롤백", applied: "적용됨", notApplied: "적용 안 됨", rooms: "방", meetings: "회의", documents: "문서", costs: "비용 기록", noApprovals: "대기 중이거나 최근 승인이 없습니다.", sessionsAndRuns: "세션 및 실행", sessions: "세션", revision: "리비전", noRuns: "실행이 없습니다.", cancel: "취소", cancelRejected: "공급자가 취소 요청을 수락하지 않았습니다.", approve: "승인", deny: "거부", approved: "승인됨", denied: "거부됨" },
};
export function translate(locale: Locale, key: MessageKey): string { return lifecycleLocales[locale]?.[key as keyof typeof lifecycleLocales.en] ?? approvalLocales[locale]?.[key as keyof typeof approval] ?? deliveryLocales[locale]?.[key as keyof typeof delivery] ?? workflowLocales[locale]?.[key as WorkflowKey] ?? messages[locale]?.[key] ?? messages.en[key] ?? `[missing:${key}]`; }
const failureKeyByIdentifier: Record<string, Extract<MessageKey, `failure${string}`>> = {
  provider_unavailable: "failureProviderUnavailable", "mvp.failure.provider_unavailable": "failureProviderUnavailable",
  provider_timeout: "failureProviderTimeout", "mvp.failure.provider_timeout": "failureProviderTimeout",
  provider_crashed: "failureProviderCrashed", "mvp.failure.provider_crashed": "failureProviderCrashed",
  provider_authentication: "failureProviderAuthentication", "mvp.failure.provider_authentication": "failureProviderAuthentication",
  provider_quota: "failureProviderQuota", "mvp.failure.provider_quota": "failureProviderQuota",
  provider_rejected: "failureProviderRejected", "mvp.failure.provider_rejected": "failureProviderRejected",
  invalid_output: "failureInvalidOutput", "mvp.failure.invalid_output": "failureInvalidOutput",
  cancelled: "failureCancelled", "mvp.failure.cancelled": "failureCancelled",
  interrupted: "failureInterrupted", "mvp.failure.interrupted": "failureInterrupted",
};
export function translateFailure(failureKind: string | null | undefined, failureMessageKey: string | null | undefined, locale: Locale): string {
  return translate(locale, failureKeyByIdentifier[failureMessageKey ?? ""] ?? failureKeyByIdentifier[failureKind ?? ""] ?? "failureUnknown");
}
export function hasExplicitWorkflowTranslation(locale: Locale, key: WorkflowKey): boolean { return Boolean(workflowLocales[locale][key]?.trim()); }
export { workflowKeys };
